-- Users table
CREATE TABLE users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    kakao_id VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT chk_users_userid_len CHECK (CHAR_LENGTH(user_id) BETWEEN 2 AND 20),
    CONSTRAINT chk_users_userid_chars CHECK (user_id REGEXP '^[A-Za-z0-9_]+$'),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);